/*CREATE TABLE Log_Activitati (
    id_eveniment INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_eveniment TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_name VARCHAR2(50),
    tip_operatie VARCHAR2(50),
    tip_obiect VARCHAR2(50),
    nume_obiect VARCHAR2(255),
    descriere_operatie VARCHAR2(500)
);
*/
CREATE OR REPLACE TRIGGER Monitorizare_Activitati_tabel
AFTER CREATE OR ALTER OR DROP ON SCHEMA
DECLARE
descriere VARCHAR2(500);
BEGIN
    --Aici am creat o conditie ca orice nou tabel creat de utilizator sa inceapa cu test_
    IF ORA_SYSEVENT = 'CREATE' AND ORA_DICT_OBJ_TYPE = 'TABLE' THEN
    IF NOT ORA_DICT_OBJ_NAME LIKE 'TEST_%' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Numele tabelului trebuie să înceapă cu TEST_!!!');
    END IF;
END IF;
    --am pus toate datele intr-o singura variabile 
     descriere := 'Utilizatorul ' || USER || ' a efectuat operația ' || ORA_SYSEVENT ||' asupra obiectului de tip ' || ORA_DICT_OBJ_TYPE ||  ' numit ' || ORA_DICT_OBJ_NAME || '.';
    INSERT INTO Log_Activitati(data_eveniment, user_name, tip_operatie, tip_obiect, nume_obiect,descriere_operatie)
    VALUES (
        SYSDATE,               
        USER,                  
        ORA_SYSEVENT,         
        ORA_DICT_OBJ_TYPE,     
        ORA_DICT_OBJ_NAME,    
        descriere
    );
    
    IF ORA_DICT_OBJ_TYPE = 'TABLE' THEN
        DBMS_OUTPUT.PUT_LINE('S-a efectuat o schimbare asupra unei tabele');
    END IF;

    
END;
/


create table TEST_tabel1(i INT);
create table tabel1(i INT);
SELECT * FROM Log_activitati;
drop table test_tabel1;
DELETE FROM log_activitati;
